[build]
build_type = Release
# source_dir = .          # project source dir, leave empty for "."
# output_dir = output     # build output dir, leave empty for "build"
generator = Ninja
parallel_jobs = auto

[compiler]
c_compiler = gcc
cpp_compiler = g++

[conan]
enable = 1
build = gcc
host = gcc

[vcpkg]
enable = 1
# root = /path/to/vcpkg                  # 默认也可使用环境变量 VCPKG_ROOT
# toolchain_file = /path/to/vcpkg.cmake  # 非空时优先于 root
# triplet = x64-linux                    # 留空时由 vcpkg 根据当前编译器自动推断

[toolchain]
custom_file = cbuild_custom.cmake

[msvc]
enable = 1
msvc_env_script = D:/Develop/Visual Studio/2019/Community/VC/Auxiliary/Build/vcvarsall.bat
host_arch = x64
